apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-backchat
  title: '@backstage/plugin-backchat'
spec:
  lifecycle: experimental
  type: backstage-frontend-plugin
  owner: benwilcock
